language: python
python:
  - "3.6"
install:
  - "python -m pip install --upgrade -r requirements.txt"
  - "python -m pip install --upgrade -r requirements_dev.txt"
  - python setup.py develop
script:
  - python setup.py test
